name: Test project
on: push
jobs:
  gradle-build-test: 
    runs-on: ubuntu-latest
    steps: 
      - name: Get Code
        uses: actions/checkout
      - name: Set up Java	
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
      - name: Setup Gradle
        with:
          gradle-version: wrapper
      - name: Execute Gradle Build
        run: ./gradlew clean build

  

