name: Test project
on: 
  push:
    branches:
      - 'main'
      - 'releases/**'
jobs:
  gradle-build-test: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      - name: Execute Gradle Build
        run: ./gradlew clean build
  report:
    needs: gradle-build-test
    runs-on: ubuntu-latest
    steps:
      - name: print-complete
        run: echo "Workflow complete"
  

